openapi: 3.0.0
info:
  contact: {}
  description: Esta API REST ofrece endpoints para obtener detalles de informes de
    analistas.
  termsOfService: http://swagger.io/terms/
  title: Analyst Reports Raw Text API
  version: 1.0.0
paths:
  /analyst/reports/raw-text:
    get:
      description: Recupera texto sin procesar de informes de investigación de
        analistas profesionales. Devuelve informes de analistas en texto
        completo, notas de investigación y recomendaciones de inversión de
        instituciones financieras. Incluye metadatos del informe, cambios de
        calificación, precios objetivo y análisis detallado. Es esencial para
        acceder a la investigación institucional y al sentimiento de los
        analistas.
      operationId: get-analyst-reports-raw-text-data
      parameters:
        - description: "Número de página para la paginación. Indexada desde cero (0 =
            primera página, 1 = segunda página, etc.). Valor predeterminado: 0"
          in: query
          name: page
          schema:
            type: integer
        - description: "Número de resultados por página. Valor predeterminado: 100.
            Máximo: 100. Devuelve primero los informes más recientes."
          in: query
          name: pagesize
          schema:
            type: integer
      responses:
        "200":
          description: Array de informes de analistas con texto íntegro y metadatos
          content:
            application/json:
              schema:
                items:
                  $ref: "#/components/schemas/models.AnalystReportRawText"
                type: array
        "400":
          description: Solicitud incorrecta - parámetros no válidos
          content:
            application/json:
              schema:
                items:
                  type: string
                type: array
        "500":
          description: Error interno del servidor
          content:
            application/json:
              schema:
                items:
                  type: string
                type: array
      security:
        - ApiKeyAuth: []
      summary: Informes de analistas
      tags:
        - Analyst Reports
components:
  securitySchemes:
    ApiKeyAuth:
      in: query
      name: token
      type: apiKey
  schemas:
    models.AnalystReportRawText:
      properties:
        date:
          example: 2024-01-09
          type: string
        exchange:
          example: NASDAQ
          type: string
        extracted_paragraphs:
          items:
            type: string
          type: array
        firm_id:
          example: GS-12345
          type: string
        id:
          example: 507f1f77bcf86cd799439011
          type: string
        ticker:
          example: AAPL
          type: string
      type: object
