openapi: 3.0.0
info:
  contact: {}
  description: Esta API REST proporciona endpoints para buscar transcripciones de
    conferencias de resultados y obtener detalles de las transcripciones de
    conferencias de resultados.
  termsOfService: http://swagger.io/terms/
  title: Earnings Call Transcripts API
  version: 1.0.0
paths:
  /api/v1/earnings-call-transcripts:
    get:
      description: Recupera transcripciones de llamadas de resultados para las
        empresas o ID de llamada especificados. Devuelve transcripciones de
        texto completo de las llamadas de resultados trimestrales y anuales,
        incluidas las sesiones de preguntas y respuestas, la identificación de
        los oradores y las marcas de tiempo. Usa filtros de fecha para recuperar
        transcripciones de períodos de informes específicos o filtra por
        símbolos de ticker para obtener debates de resultados específicos de
        cada empresa.
      operationId: get-earnings-call-transcripts
      parameters:
        - description: Lista de símbolos de ticker bursátiles separados por comas para
            filtrar transcripciones de llamadas de resultados (por ejemplo,
            AAPL, MSFT, GOOGL). Devuelve todas las transcripciones de estas
            compañías.
          in: query
          name: tickers
          style: form
          explode: false
          schema:
            type: array
            items:
              type: string
        - description: Lista de IDs de llamadas específicas, separadas por comas, que se
            deben recuperar. Utilice esto para obtener transcripciones de
            llamadas de resultados con identificadores conocidos. Tiene
            prioridad sobre el filtrado por ticker.
          in: query
          name: call_id
          style: form
          explode: false
          schema:
            type: array
            items:
              type: string
        - description: "Número de página para la paginación. Indexado desde cero (0 =
            primera página, 1 = segunda página, etc.). Predeterminado: 0"
          in: query
          name: page
          schema:
            type: integer
        - description: "Número de resultados por página. Valor predeterminado: 5. Máximo:
            1000. Use tamaños de página más grandes para obtener grandes
            volúmenes de datos."
          in: query
          name: pagesize
          schema:
            type: integer
        - description: Filtro de fecha de inicio en formato AAAA-MM-DD (por ejemplo,
            2024-01-01). Devuelve transcripciones de conferencias de resultados
            a partir de esta fecha.
          in: query
          name: date_from
          schema:
            type: string
        - description: Filtro de fecha de finalización en formato AAAA-MM-DD (p. ej.,
            2024-12-31). Devuelve transcripciones de llamadas de resultados
            hasta esta fecha incluida.
          in: query
          name: date_to
          schema:
            type: string
      responses:
        "200":
          description: Array de resúmenes de las transcripciones de las llamadas de
            resultados con texto completo y metadatos
          content:
            application/json:
              schema:
                items:
                  $ref: "#/components/schemas/models.TranscriptSummary"
                type: array
        "400":
          description: Solicitud incorrecta - parámetros no válidos
          content:
            application/json:
              schema:
                items:
                  type: string
                type: array
        "500":
          description: Error interno del servidor
          content:
            application/json:
              schema:
                items:
                  type: string
                type: array
      security:
        - ApiKeyAuth: []
      summary: Transcripciones de llamadas de resultados
      tags:
        - Earnings Call Transcripts
  /api/v1/earnings-call-transcripts/audio:
    get:
      description: Obtiene URLs de archivos de audio descargables de grabaciones de
        conferencias de resultados. Devuelve URLs firmadas para acceder a las
        grabaciones de audio completas de las conferencias de resultados
        trimestrales y anuales. Los archivos de audio incluyen las
        presentaciones completas de resultados y las sesiones de preguntas y
        respuestas. Las URLs son de duración limitada y están firmadas de forma
        segura para el acceso autorizado.
      operationId: get-earnings-call-transcript-audio-files
      parameters:
        - description: Lista de símbolos de ticker de acciones, separados por comas, para
            filtrar archivos de audio (por ejemplo, AAPL,MSFT,GOOGL). Devuelve
            archivos de audio de todas las llamadas de resultados de estas
            empresas.
          in: query
          name: tickers
          style: form
          explode: false
          schema:
            type: array
            items:
              type: string
        - description: Lista de identificadores de llamadas específicos, separados por
            comas, para recuperar archivos de audio. Utilice esto para obtener
            el audio de identificadores de llamadas de resultados conocidos.
          in: query
          name: call_id
          style: form
          explode: false
          schema:
            type: array
            items:
              type: string
        - description: "Número de página para la paginación. Indexado a partir de cero (0
            = primera página, 1 = segunda página, etc.). Valor predeterminado:
            0"
          in: query
          name: page
          schema:
            type: integer
        - description: "Número de resultados por página. Valor predeterminado: 5. Máximo:
            1000"
          in: query
          name: pagesize
          schema:
            type: integer
      responses:
        "200":
          description: Array de metadatos de archivos de audio de conferencias de
            resultados con URL de descarga firmadas
          content:
            application/json:
              schema:
                items:
                  $ref: "#/components/schemas/models.TranscriptSummaryAudio"
                type: array
        "400":
          description: Solicitud incorrecta - parámetros no válidos
          content:
            application/json:
              schema:
                items:
                  type: string
                type: array
        "500":
          description: Error interno del servidor
          content:
            application/json:
              schema:
                items:
                  type: string
                type: array
      security:
        - ApiKeyAuth: []
      summary: Archivos de audio de llamadas de resultados
      tags:
        - Earnings Call Transcripts
components:
  securitySchemes:
    ApiKeyAuth:
      in: query
      name: token
      type: apiKey
  schemas:
    models.Security:
      properties:
        cik:
          example: "320193"
          type: string
        company_name:
          example: Apple Inc
          type: string
        exchange:
          example: NASDAQ
          type: string
        isin:
          example: US0378331005
          type: string
        ticker:
          example: AAPL
          type: string
      type: object
    models.Summary:
      properties:
        summary:
          example: CEO discusses Q4 revenue growth of 15% YoY
          type: string
        time:
          example: 123.45
          type: number
      type: object
    models.TranscriptAudioFile:
      properties:
        file_url:
          type: string
      type: object
    models.TranscriptSummary:
      properties:
        call_id:
          example: AAPL-Q4-2024
          type: string
        created:
          example: 1704819600
          type: integer
        date:
          example: 2024-01-09
          type: string
        id:
          example: 507f1f77bcf86cd799439011
          type: string
        reviewed:
          example: true
          type: boolean
        security:
          $ref: "#/components/schemas/models.Security"
        start_time:
          example: 2024-01-09T16:30:00Z
          type: string
        summaries:
          items:
            $ref: "#/components/schemas/models.Summary"
          type: array
        summary_full:
          type: string
        title:
          example: Apple Q4 2024 Earnings Call
          type: string
        transcript_full:
          type: string
        transcript_timestamped:
          items:
            $ref: "#/components/schemas/models.TranscriptTimestamp"
          type: array
        updated:
          example: 1704820200
          type: integer
        user_id:
          example: 12345
          type: integer
      type: object
    models.TranscriptSummaryAudio:
      properties:
        audio_file:
          $ref: "#/components/schemas/models.TranscriptAudioFile"
        call_id:
          type: string
        created:
          type: integer
        date:
          type: string
        id:
          type: string
        security:
          $ref: "#/components/schemas/models.Security"
        start_time:
          type: string
        updated:
          type: integer
      type: object
    models.TranscriptTimestamp:
      properties:
        time:
          example: 123.45
          type: number
        transcript:
          example: Thank you for joining us today...
          type: string
      type: object
