openapi: 3.0.0
info:
  contact: {}
  description: 이 REST API는 실적 발표 컨퍼런스 콜 녹취록 검색 및 상세 조회를 위한 엔드포인트를 제공합니다.
  termsOfService: http://swagger.io/terms/
  title: Earnings Call Transcripts API
  version: 1.0.0
paths:
  /api/v1/earnings-call-transcripts:
    get:
      description: 지정한 기업 또는 콜 ID에 대한 실적 발표 컨퍼런스 콜 녹취록을 조회합니다. 분기 및 연간 실적 발표 콜의 전체 텍스트
        녹취록을 Q&A 세션, 발표자 정보, 타임스탬프와 함께 반환합니다. 날짜 필터를 사용해 특정 보고 기간의 녹취록을 조회하거나 티커
        심볼로 필터링하여 개별 기업의 실적 발표 내용을 조회할 수 있습니다.
      operationId: get-earnings-call-transcripts
      parameters:
        - description: "실적 발표 콜 녹취록을 필터링하는 데 사용하는 주식 티커 심볼의 콤마(,)로 구분된 목록입니다(예:
            AAPL,MSFT,GOOGL). 이들 기업의 모든 녹취록을 반환합니다."
          in: query
          name: tickers
          style: form
          explode: false
          schema:
            type: array
            items:
              type: string
        - description: 가져올 특정 콜 ID를 콤마로 구분한 목록입니다. 이미 알고 있는 실적 발표 콜 식별자의 트랜스크립트를 조회할 때
            사용합니다. 티커 필터링보다 우선 적용됩니다.
          in: query
          name: call_id
          style: form
          explode: false
          schema:
            type: array
            items:
              type: string
        - description: "페이지네이션용 페이지 번호입니다. 0부터 시작하는 0-인덱스입니다(0 = 첫 번째 페이지, 1 = 두 번째 페이지
            등). 기본값: 0"
          in: query
          name: page
          schema:
            type: integer
        - description: "페이지당 반환되는 결과 수입니다. 기본값: 5, 최대값: 1000. 대량 데이터 조회 시 더 큰 페이지 크기를
            사용하세요."
          in: query
          name: pagesize
          schema:
            type: integer
        - description: "YYYY-MM-DD 형식의 시작 날짜 필터입니다(예: 2024-01-01). 이 날짜 당일 및 이후의 실적 발표 콜
            transcript를 반환합니다."
          in: query
          name: date_from
          schema:
            type: string
        - description: "YYYY-MM-DD 형식의 종료일 필터입니다(예: 2024-12-31). 이 날짜까지의 실적 발표 컨퍼런스
            콜(transcripts)을 반환합니다."
          in: query
          name: date_to
          schema:
            type: string
      responses:
        "200":
          description: 전체 텍스트와 메타데이터가 포함된 실적 발표 콘퍼런스콜 회의록 요약 배열
          content:
            application/json:
              schema:
                items:
                  $ref: "#/components/schemas/models.TranscriptSummary"
                type: array
        "400":
          description: 잘못된 요청 - 잘못된 파라미터
          content:
            application/json:
              schema:
                items:
                  type: string
                type: array
        "500":
          description: 내부 서버 오류
          content:
            application/json:
              schema:
                items:
                  type: string
                type: array
      security:
        - ApiKeyAuth: []
      summary: 실적 발표 콘퍼런스콜 녹취록
      tags:
        - Earnings Call Transcripts
  /api/v1/earnings-call-transcripts/audio:
    get:
      description: 실적 발표 콜 녹음에 대한 다운로드용 오디오 파일 URL을 조회합니다. 분기 및 연간 실적 발표 콜 전체 오디오 녹음에
        액세스할 수 있는 서명된 URL을 반환합니다. 오디오 파일에는 전체 실적 발표 프레젠테이션과 Q&A 세션이 포함됩니다. URL은
        유효 기간이 제한되어 있으며, 인가된 액세스만 가능하도록 안전하게 서명됩니다.
      operationId: get-earnings-call-transcript-audio-files
      parameters:
        - description: "오디오 파일을 필터링하기 위한 주식 티커 심볼의 쉼표로 구분된 목록입니다(예: AAPL,MSFT,GOOGL). 이들
            회사의 모든 실적 발표 콜 오디오 파일을 반환합니다."
          in: query
          name: tickers
          style: form
          explode: false
          schema:
            type: array
            items:
              type: string
        - description: 가져올 오디오 파일의 개별 콜 ID를 쉼표로 구분한 목록입니다. 이미 알고 있는 실적 발표 콜 식별자의 오디오를 조회할
            때 사용합니다.
          in: query
          name: call_id
          style: form
          explode: false
          schema:
            type: array
            items:
              type: string
        - description: "페이지네이션용 페이지 번호입니다. 0부터 시작하는 인덱스입니다(0 = 첫 번째 페이지, 1 = 두 번째 페이지 등).
            기본값: 0"
          in: query
          name: page
          schema:
            type: integer
        - description: "페이지당 결과 수입니다. 기본값: 5, 최대값: 1000"
          in: query
          name: pagesize
          schema:
            type: integer
      responses:
        "200":
          description: 서명된 다운로드 url을 포함하는 실적 발표(어닝) 콜 오디오 파일 메타데이터 배열
          content:
            application/json:
              schema:
                items:
                  $ref: "#/components/schemas/models.TranscriptSummaryAudio"
                type: array
        "400":
          description: 잘못된 요청 - 잘못된 매개변수
          content:
            application/json:
              schema:
                items:
                  type: string
                type: array
        "500":
          description: 내부 서버 오류
          content:
            application/json:
              schema:
                items:
                  type: string
                type: array
      security:
        - ApiKeyAuth: []
      summary: 실적 발표 컨퍼런스 콜 오디오 파일
      tags:
        - Earnings Call Transcripts
components:
  securitySchemes:
    ApiKeyAuth:
      in: query
      name: token
      type: apiKey
  schemas:
    models.Security:
      properties:
        cik:
          example: "320193"
          type: string
        company_name:
          example: Apple Inc
          type: string
        exchange:
          example: NASDAQ
          type: string
        isin:
          example: US0378331005
          type: string
        ticker:
          example: AAPL
          type: string
      type: object
    models.Summary:
      properties:
        summary:
          example: CEO discusses Q4 revenue growth of 15% YoY
          type: string
        time:
          example: 123.45
          type: number
      type: object
    models.TranscriptAudioFile:
      properties:
        file_url:
          type: string
      type: object
    models.TranscriptSummary:
      properties:
        call_id:
          example: AAPL-Q4-2024
          type: string
        created:
          example: 1704819600
          type: integer
        date:
          example: 2024-01-09
          type: string
        id:
          example: 507f1f77bcf86cd799439011
          type: string
        reviewed:
          example: true
          type: boolean
        security:
          $ref: "#/components/schemas/models.Security"
        start_time:
          example: 2024-01-09T16:30:00Z
          type: string
        summaries:
          items:
            $ref: "#/components/schemas/models.Summary"
          type: array
        summary_full:
          type: string
        title:
          example: Apple Q4 2024 Earnings Call
          type: string
        transcript_full:
          type: string
        transcript_timestamped:
          items:
            $ref: "#/components/schemas/models.TranscriptTimestamp"
          type: array
        updated:
          example: 1704820200
          type: integer
        user_id:
          example: 12345
          type: integer
      type: object
    models.TranscriptSummaryAudio:
      properties:
        audio_file:
          $ref: "#/components/schemas/models.TranscriptAudioFile"
        call_id:
          type: string
        created:
          type: integer
        date:
          type: string
        id:
          type: string
        security:
          $ref: "#/components/schemas/models.Security"
        start_time:
          type: string
        updated:
          type: integer
      type: object
    models.TranscriptTimestamp:
      properties:
        time:
          example: 123.45
          type: number
        transcript:
          example: Thank you for joining us today...
          type: string
      type: object
