openapi: 3.0.0
info:
  contact: {}
  description: Bearer 토큰 인증
  title: Press Releases v2
  version: 2.0.0
paths:
  /api/v2/news:
    get:
      description: 이 REST API는 보도자료에 대한 구조화된 데이터를 반환합니다. 최적의 성능을 위해 티커, 날짜, 채널 등의
        매개변수로 쿼리 범위를 제한하거나, 변경분 조회에는 updatedSince를 사용하세요. 페이지 오프셋은 0~100000 범위로
        제한됩니다.
      operationId: get-press-releases
      parameters:
        - description: 반환 형식 지정
          in: header
          name: accept
          required: true
          schema:
            type: string
            enum:
              - application/json
              - application/xml
            default: application/json
        - description: 페이지 오프셋입니다. 최적화, 성능 및 기술적 이유로 페이지 오프셋은 0~100000 범위로 제한됩니다. 날짜 등의 다른
            매개변수로 쿼리 결과를 제한하세요.
          in: query
          name: page
          schema:
            type: integer
            default: 0
        - description: 반환되는 결과 수입니다. 최대 100개입니다.
          in: query
          name: pageSize
          schema:
            type: integer
            maximum: 100
            default: 15
        - description: 헤드라인만(headline), 헤드라인 + 요약문(abstract), 또는 헤드라인 + 전체 본문(full) 텍스트를
            지정합니다.
          in: query
          name: displayOutput
          schema:
            type: string
            enum:
              - full
              - abstract
              - headline
            default: headline
        - description: "뉴스를 조회할 날짜입니다. dateFrom과 dateTo가 같을 경우 이를 축약해 사용합니다. 형식: yyyy-mm-dd"
          in: query
          name: date
          schema:
            type: string
        - description: "조회 시작 시점의 날짜입니다. 게시일 기준으로 정렬됩니다. 형식: yyyy-mm-dd"
          in: query
          name: dateFrom
          schema:
            type: string
        - description: "조회 종료 시점의 날짜입니다. 게시일 기준으로 정렬됩니다. 형식: yyyy-mm-dd"
          in: query
          name: dateTo
          schema:
            type: string
        - description: 가져오고 정렬할 기준이 되는 마지막 업데이트 Unix 타임스탬프(UTC)입니다.
          in: query
          name: updatedSince
          schema:
            type: integer
        - description: 가져오고 정렬할 기준이 되는 마지막 게시 Unix 타임스탬프(UTC)입니다.
          in: query
          name: publishedSince
          schema:
            type: integer
        - description: "결과 정렬을 제어할 수 있습니다. 기본값은 created, DESC입니다. 형식: field:direction. 정렬
            필드: id, created, updated. 정렬 순서: asc(오름차순), desc(내림차순)"
          in: query
          name: sort
          schema:
            type: string
            enum:
              - id:asc
              - id:desc
              - created:asc
              - created:desc
              - updated:asc
              - updated:desc
        - description: "쉼표로 구분된 하나 이상의 국제증권식별번호(ISIN)입니다. 최대 50개입니다. 형식: csv"
          in: query
          name: isin
          schema:
            type: string
        - description: "쉼표로 구분된 하나 이상의 CUSIP입니다. 최대 50개입니다. 라이선스 계약이 필요합니다. 형식: csv"
          in: query
          name: cusips
          schema:
            type: string
        - description: "쉼표로 구분된 하나 이상의 티커 심볼입니다. 최대 50개입니다. 형식: csv"
          in: query
          name: tickers
          schema:
            type: string
        - description: "쉼표로 구분된 하나 이상의 기본 티커 심볼입니다. 기본 티커 연관 항목만 기준으로 필터링합니다. 형식: csv"
          in: query
          name: primaryTickers
          schema:
            type: string
        - description: "쉼표로 구분된 하나 이상의 채널 이름 또는 ID입니다. 형식: csv"
          in: query
          name: channels
          schema:
            type: string
        - description: "쉼표로 구분된 하나 이상의 단어/구문입니다. 우선순위에 따라 제목, 태그, 본문에서 검색합니다. 형식: csv"
          in: query
          name: topics
          schema:
            type: string
        - description: topics 쿼리의 논리 연산자입니다. 모든 topic이 필요하면 'and'를, 하나 이상의 topic이면 되면
            'or'를 사용하세요.
          in: query
          name: topic_group_by
          schema:
            type: string
            enum:
              - and
              - or
            default: or
        - description: "쉼표로 구분된 하나 이상의 작성자입니다. 형식: csv"
          in: query
          name: authors
          schema:
            type: string
        - description: "쉼표로 구분된 하나 이상의 콘텐츠 유형입니다. 형식: csv"
          in: query
          name: content_types
          schema:
            type: string
            default: accesswire_story,accesswire_pr,businesswire_story,newswire_pressreleases,newswire_story,globenewswire_story,newsfile_story
        - description: api 응답에 사용할 형식을 지정합니다.
          in: query
          name: format
          schema:
            type: string
            enum:
              - text
        - description: 중요도 수준으로 필터링
          in: query
          name: importance
          schema:
            type: string
            enum:
              - low
              - medium
              - high
        - description: "지역으로 필터링합니다(예: 캐나다 콘텐츠의 경우 'ca' 또는 'canada')."
          in: query
          name: region
          schema:
            type: string
      responses:
        "200":
          description: 성공
          content:
            application/json:
              schema:
                items:
                  $ref: "#/components/schemas/api.NewsItem"
                type: array
            text/xml:
              schema:
                items:
                  $ref: "#/components/schemas/api.NewsItem"
                type: array
        "400":
          description: 유효하지 않거나 누락된 쿼리 매개변수
          content:
            application/json:
              schema:
                type: string
            text/xml:
              schema:
                type: string
        "499":
          description: 요청 컨텍스트 취소됨
          content:
            application/json:
              schema:
                type: string
            text/xml:
              schema:
                type: string
        "500":
          description: 내부 오류
          content:
            application/json:
              schema:
                type: string
            text/xml:
              schema:
                type: string
      security:
        - ApiKeyAuth: []
      summary: 보도자료
      tags:
        - Press Releases
components:
  securitySchemes:
    ApiKeyAuth:
      description: API 키 인증입니다. API 키를 쿼리 매개변수로 제공하세요.
      in: query
      name: token
      type: apiKey
  schemas:
    api.ChannelTag:
      description: 채널 또는 태그 이름
      properties:
        name:
          example: Technology
          type: string
      type: object
    api.Image:
      description: 크기와 URL이 포함된 기사 이미지
      properties:
        size:
          example: large
          type: string
        url:
          example: https://cdn.benzinga.com/files/images/story/2024/example.jpg
          type: string
      type: object
    api.NewsItem:
      description: 전체 메타데이터가 포함된 뉴스 기사 항목
      properties:
        author:
          example: Benzinga Newsdesk
          type: string
        body:
          type: string
        channels:
          items:
            $ref: "#/components/schemas/api.ChannelTag"
          type: array
        created:
          example: Wed, 17 May 2017 14:20:15 -0400
          type: string
        id:
          example: 123456
          type: integer
        image:
          items:
            $ref: "#/components/schemas/api.Image"
          type: array
        original_id:
          type: integer
        stocks:
          items:
            $ref: "#/components/schemas/api.Stock"
          type: array
        tags:
          items:
            $ref: "#/components/schemas/api.ChannelTag"
          type: array
        teaser:
          type: string
        title:
          example: Apple Announces New iPhone
          type: string
        updated:
          example: Wed, 17 May 2017 14:20:15 -0400
          type: string
        url:
          example: https://www.benzinga.com/news/123456
          type: string
      type: object
    api.NewsRemovedItem:
      description: ID와 업데이트 타임스탬프가 포함된 삭제된 뉴스 기사 항목
      properties:
        id:
          example: 123456
          type: integer
        updated:
          example: Wed, 17 May 2017 14:20:15 -0400
          type: string
      type: object
    api.Stock:
      description: 티커 심볼과 식별자가 포함된 종목 정보
      properties:
        cusip:
          example: "037833100"
          type: string
        exchange:
          example: NASDAQ
          type: string
        isin:
          example: US0378331005
          type: string
        name:
          example: AAPL
          type: string
      type: object
servers:
  - url: https://api.benzinga.com
    description: PROD
