openapi: 3.0.0
info:
  contact: {}
  description: このREST APIは、アナリストレポートの詳細を取得するためのエンドポイントを提供します。
  termsOfService: http://swagger.io/terms/
  title: Analyst Reports Raw Text API
  version: 1.0.0
paths:
  /analyst/reports/raw-text:
    get:
      description: プロのアナリストレポートのテキスト生データを取得します。金融機関によるアナリストレポートの全文、リサーチノート、および投資推奨を返します。レポートのメタデータ、レーティング変更、目標株価、詳細な分析を含みます。機関投資家向けリサーチおよびアナリストセンチメントにアクセスするために不可欠なデータです。
      operationId: get-analyst-reports-raw-text-data
      parameters:
        - description: "ページネーション用のページ番号。0から始まります（0 = 1ページ目、1 = 2ページ目、など）。デフォルト: 0"
          in: query
          name: page
          schema:
            type: integer
        - description: "1ページあたりの結果数。デフォルト値: 100。最大値: 100。最新のレポートから順に返されます。"
          in: query
          name: pagesize
          schema:
            type: integer
      responses:
        "200":
          description: 全文テキストとメタデータを含むアナリストレポートの配列
          content:
            application/json:
              schema:
                items:
                  $ref: "#/components/schemas/models.AnalystReportRawText"
                type: array
        "400":
          description: 不正なリクエスト - 無効なパラメータ
          content:
            application/json:
              schema:
                items:
                  type: string
                type: array
        "500":
          description: 内部サーバーエラー
          content:
            application/json:
              schema:
                items:
                  type: string
                type: array
      security:
        - ApiKeyAuth: []
      summary: アナリストレポート
      tags:
        - Analyst Reports
components:
  securitySchemes:
    ApiKeyAuth:
      in: query
      name: token
      type: apiKey
  schemas:
    models.AnalystReportRawText:
      properties:
        date:
          type: string
        exchange:
          type: string
        extracted_paragraphs:
          items:
            type: string
          type: array
        firm_id:
          type: string
        id:
          type: string
        ticker:
          type: string
      type: object
