openapi: 3.0.0
info:
  contact: {}
  description: この REST API では、決算説明会のトランスクリプトを検索したり、その詳細を取得したりするためのエンドポイントを提供します。
  termsOfService: http://swagger.io/terms/
  title: Earnings Call Transcripts API
  version: 1.0.0
paths:
  /api/v1/earnings-call-transcripts:
    get:
      description: 指定した企業またはコールIDの決算説明会の書き起こしを取得します。四半期および通期の決算説明会について、質疑応答セッション、話者の識別情報、タイムスタンプを含む全文書き起こしを返します。日付フィルターを使用して特定の会計期間の書き起こしを取得するか、ticker
        シンボル（カンマ区切りのシンボル一覧）でフィルタリングして、特定企業の決算説明会に関するコールのみを取得します。
      operationId: get-earnings-call-transcripts
      parameters:
        - description: "決算説明会トランスクリプトを絞り込むための株式tickerシンボルのカンマ区切りリスト（例:
            AAPL,MSFT,GOOGL）。これらの企業のすべての決算説明会トランスクリプトを返します。"
          in: query
          name: tickers
          style: form
          explode: false
          schema:
            type: array
            items:
              type: string
        - description: 取得する特定のコールIDのカンマ区切りリスト。既知の決算説明会コールIDに対応するトランスクリプトを取得するために使用します。ticker
            ベースのフィルタリングよりも優先されます。
          in: query
          name: call_id
          style: form
          explode: false
          schema:
            type: array
            items:
              type: string
        - description: ページネーション用のページ番号。0始まり（ゼロ基準）です（0 = 1ページ目、1 = 2ページ目、など）。デフォルト：0
          in: query
          name: page
          schema:
            type: integer
        - description: "1ページあたりの結果数。デフォルト値: 5、最大値: 1000。大量データを取得する場合は、より大きなページサイズを使用してください。"
          in: query
          name: pagesize
          schema:
            type: integer
        - description: "YYYY-MM-DD 形式の開始日フィルター（例:
            2024-01-01）。この日付以降の決算発表電話会議のトランスクリプトを返します。"
          in: query
          name: date_from
          schema:
            type: string
        - description: "終了日フィルターを YYYY-MM-DD 形式（例:
            2024-12-31）で指定します。この日付を含むそれ以前の決算説明会のトランスクリプトを返します。"
          in: query
          name: date_to
          schema:
            type: string
      responses:
        "200":
          description: 決算説明会の書き起こし要約（全文テキストおよびメタデータ付き）の配列
          content:
            application/json:
              schema:
                items:
                  $ref: "#/components/schemas/models.TranscriptSummary"
                type: array
        "400":
          description: 不正なリクエスト - パラメータが無効です
          content:
            application/json:
              schema:
                items:
                  type: string
                type: array
        "500":
          description: 内部サーバーエラー
          content:
            application/json:
              schema:
                items:
                  type: string
                type: array
      security:
        - ApiKeyAuth: []
      summary: 決算説明会の書き起こし
      tags:
        - Earnings Call Transcripts
  /api/v1/earnings-call-transcripts/audio:
    get:
      description: 決算説明会音声のダウンロード用URLを取得します。四半期および通期の決算説明会の完全な音声録音にアクセスするための署名付きURLを返します。音声ファイルには、決算プレゼンテーション全体とQ&Aセッションが含まれます。URLには有効期限があり、認可されたアクセスのみが可能となるよう署名されています。
      operationId: get-earnings-call-transcript-audio-files
      parameters:
        - description: "音声ファイルを絞り込むための株式tickerシンボルのカンマ区切りリスト（例:
            AAPL,MSFT,GOOGL）。これらの企業のすべての決算説明会の音声ファイルを返します。"
          in: query
          name: tickers
          style: form
          explode: false
          schema:
            type: array
            items:
              type: string
        - description: 音声ファイルを取得する対象の特定のコールIDをカンマ区切りで指定したリスト。既知の決算説明会コールの識別子に対する音声を取得するために使用します。
          in: query
          name: call_id
          style: form
          explode: false
          schema:
            type: array
            items:
              type: string
        - description: "ページネーションのページ番号。0始まり（ゼロインデックス）です。0 が 1 ページ目、1 が 2
            ページ目というように指定します。デフォルト値: 0"
          in: query
          name: page
          schema:
            type: integer
        - description: "1ページあたりの結果数。デフォルト: 5。最大: 1000"
          in: query
          name: pagesize
          schema:
            type: integer
      responses:
        "200":
          description: 署名付きダウンロードURLを含む決算説明会音声ファイルメタデータの配列
          content:
            application/json:
              schema:
                items:
                  $ref: "#/components/schemas/models.TranscriptSummaryAudio"
                type: array
        "400":
          description: 不正なリクエスト - 無効なパラメータ
          content:
            application/json:
              schema:
                items:
                  type: string
                type: array
        "500":
          description: サーバ内部エラー
          content:
            application/json:
              schema:
                items:
                  type: string
                type: array
      security:
        - ApiKeyAuth: []
      summary: 決算説明会の書き起こし音声ファイル
      tags:
        - Earnings Call Transcripts
components:
  securitySchemes:
    ApiKeyAuth:
      in: query
      name: token
      type: apiKey
  schemas:
    models.Security:
      properties:
        cik:
          type: string
        company_name:
          type: string
        exchange:
          type: string
        isin:
          type: string
        ticker:
          type: string
      type: object
    models.Summary:
      properties:
        summary:
          type: string
        time:
          type: number
      type: object
    models.TranscriptAudioFile:
      properties:
        file_url:
          type: string
      type: object
    models.TranscriptSummary:
      properties:
        call_id:
          type: string
        created:
          type: integer
        date:
          type: string
        id:
          type: string
        reviewed:
          type: boolean
        security:
          $ref: "#/components/schemas/models.Security"
        start_time:
          type: string
        summaries:
          items:
            $ref: "#/components/schemas/models.Summary"
          type: array
        summary_full:
          type: string
        title:
          type: string
        transcript_full:
          type: string
        transcript_timestamped:
          items:
            $ref: "#/components/schemas/models.TranscriptTimestamp"
          type: array
        updated:
          type: integer
        user_id:
          type: integer
      type: object
    models.TranscriptSummaryAudio:
      properties:
        audio_file:
          $ref: "#/components/schemas/models.TranscriptAudioFile"
        call_id:
          type: string
        created:
          type: integer
        date:
          type: string
        id:
          type: string
        security:
          $ref: "#/components/schemas/models.Security"
        start_time:
          type: string
        updated:
          type: integer
      type: object
    models.TranscriptTimestamp:
      properties:
        time:
          type: number
        transcript:
          type: string
      type: object
