openapi: 3.0.0
info:
  contact: {}
  description: この REST API は、ロゴ検索およびロゴの詳細取得用のエンドポイントを提供します。
  termsOfService: http://swagger.io/terms/
  title: Logo API
  version: 2.1.0
paths:
  /api/v2.1/logos/sync:
    get:
      description: ロゴの一括同期
      operationId: logo-bulk-sync
      parameters:
        - description: 証券識別子または取引所 MIC コードのカンマ区切りリスト（v2.1 の exchange ロゴ用）。タイプは
            search_keys_type パラメータに依存します。
          in: query
          name: search_keys
          required: true
          schema:
            type: string
        - description: 検索対象の識別子の種類。サポートされるタイプ：symbol（デフォルト）、CIK、CUSIP、ISIN、exchange（v2.1 のみ）
          in: query
          name: search_keys_type
          schema:
            type: string
        - description: "返却するロゴフィールドをカンマ区切りのリストで指定します。最大 12 個まで指定可能です。利用可能なフィールド:
            logo_light, logo_dark, logo_vector_light, logo_vector_dark,
            mark_light, mark_dark, mark_vector_light, mark_vector_dark,
            mark_composite_light, mark_composite_dark,
            mark_vector_composite_light, mark_vector_composite_dark, colors"
          in: query
          name: fields
          required: true
          style: form
          explode: false
          schema:
            type: array
            items:
              type: string
        - description: ページング用のページ番号です。一括同期処理では pagesize と組み合わせて使用します。
          in: query
          name: page
          schema:
            type: integer
        - description: "1ページあたりの結果数。デフォルト値: 100。最大値: 1000"
          in: query
          name: pagesize
          schema:
            type: integer
        - description: Unixタイムスタンプ（UTC）。このタイムスタンプより後に更新されたロゴのみを返します。
          in: query
          name: updated_since
          schema:
            type: string
        - description: "画像のサイズを WIDTHxHEIGHT 形式（例:
            300x300）で指定します。画像は縮小のみ行われ、拡大はされません。デフォルト値: 300x300"
          in: query
          name: scale
          schema:
            type: string
        - description: "合成画像の角丸半径（パーセンテージ指定）。指定可能な範囲は 0～50 で、50 を指定すると円形になります。デフォルト値: 0"
          in: query
          name: composite_radius
          schema:
            type: integer
      responses:
        "200":
          description: data フィールドに BulkSyncResponse オブジェクトの配列を含む成功時のレスポンス
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/bzhttp.Resp"
        "400":
          description: 不正なリクエスト - パラメータが無効か不足しています
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/bzhttp.Resp"
        "404":
          description: 見つかりません - 条件に一致するロゴは見つかりませんでした
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/bzhttp.Resp"
        "500":
          description: サーバー内部エラー
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/bzhttp.Resp"
      security:
        - ApiKeyAuth: []
      summary: ロゴ一括同期
      tags:
        - logos
  /api/v2/logos/search:
    get:
      description: ロゴ検索
      operationId: get-search-logos
      parameters:
        - description: カンマ区切りの証券識別子のリストです。識別子は最大 100 個まで指定できます。識別子の種別は search_keys_type
            パラメータに依存します。
          in: query
          name: search_keys
          required: true
          schema:
            type: string
        - description: 検索する識別子の種別。サポートされる種別は symbol（デフォルト）、CIK、CUSIP、ISIN です。
          in: query
          name: search_keys_type
          schema:
            type: string
        - description: "返却するロゴフィールドのカンマ区切りリスト。最大 12 個まで指定可能です。指定可能なフィールド: logo_light,
            logo_dark, logo_vector_light, logo_vector_dark, mark_light,
            mark_dark, mark_vector_light, mark_vector_dark,
            mark_composite_light, mark_composite_dark,
            mark_vector_composite_light, mark_vector_composite_dark, colors"
          in: query
          name: fields
          required: true
          schema:
            type: string
        - description: true で、かつロゴが存在しない場合、企業名とブランドカラーに基づく合成画像を生成します
          in: query
          name: composite_auto
          schema:
            type: boolean
        - description: "合成画像の角丸（% 単位）。値の範囲は 0～50 で、50 に設定すると円形になります。デフォルト値: 0"
          in: query
          name: composite_radius
          schema:
            type: integer
        - description: "画像の寸法を WIDTHxHEIGHT 形式で指定します（例:
            300x300）。画像は縮小のみ行われ、拡大は行われません。デフォルト値: 300x300"
          in: query
          name: scale
          schema:
            type: string
        - description: スケーリングされた画像の最大幅の制約（ピクセル単位）
          in: query
          name: max_width
          schema:
            type: string
        - description: true の場合、flutter_svg ライブラリとの互換性を保つために、SVG の URL にクエリパラメータ
            flutter_compatible=true を追加します。
          in: query
          name: flutter_compatible
          schema:
            type: boolean
      responses:
        "200":
          description: data フィールドに LogoClientResponse オブジェクトの配列を含む成功したレスポンス
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/bzhttp.Resp"
        "400":
          description: 不正なリクエスト - パラメーターが無効または不足しています
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/bzhttp.Resp"
        "404":
          description: 見つかりません - 指定された検索キーに一致するロゴは見つかりませんでした
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/bzhttp.Resp"
        "500":
          description: 内部サーバーエラー
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/bzhttp.Resp"
      security:
        - ApiKeyAuth: []
      summary: ロゴ検索
      tags:
        - logos
components:
  securitySchemes:
    ApiKeyAuth:
      in: query
      name: token
      type: apiKey
  schemas:
    bzhttp.Error:
      properties:
        code:
          $ref: "#/components/schemas/bzhttp.ErrorCode"
        id:
          type: string
        value:
          type: string
      type: object
    bzhttp.ErrorCode:
      enum:
        - unsupported_message_type
        - database_query_error
        - json_unmarshaling_error
        - no_data_found
        - no_matching_endpoint
        - bad_request
        - db_error
        - internal_server_error
        - auth_failed
        - forbidden
        - failed_dependency
        - service_unavailable
        - upstream_api_error
      type: string
      x-enum-varnames:
        - ErrorUnsupportedMessageType
        - ErrorDBQueryError
        - ErrorJSONUnmarshaling
        - ErrorNoDataFound
        - ErrorNoMatchingEndpoint
        - ErrorBadRequest
        - ErrorDBError
        - ErrorInternalServerError
        - ErrorAuthFailed
        - ErrorForbidden
        - ErrorFailedDependency
        - ErrorServiceUnavailable
        - ErrorUpstreamAPIError
    bzhttp.Resp:
      properties:
        data:
          additionalProperties: true
          type: object
        errors:
          items:
            $ref: "#/components/schemas/bzhttp.Error"
          type: array
        ok:
          type: boolean
      type: object
