openapi: 3.0.0
info:
  contact: {}
  description: Autenticación mediante token Bearer
  title: Newsfeed & Why is it Moving v2
  version: 2.0.0
paths:
  /api/v2.1/news/channels:
    get:
      description: Devuelve una lista de todos los canales de noticias disponibles que
        se pueden utilizar para filtrar las noticias. Los canales pueden tener
        subcanales, pero todos aparecerán listados como elementos individuales.
      operationId: get-channels
      responses:
        "200":
          description: éxito
          content:
            application/json:
              schema:
                additionalProperties: true
                type: object
        "500":
          description: Error interno del servidor
          content:
            application/json:
              schema:
                additionalProperties: true
                type: object
      summary: Obtener los canales de noticias disponibles
      tags:
        - Channels
  /api/v2/news:
    get:
      description: Esta API REST devuelve datos estructurados de noticias. Para un
        rendimiento óptimo, limite el alcance de la consulta mediante parámetros
        como símbolos bursátiles, fecha y canales, o use updatedSince para
        obtener solo los cambios (deltas). Los offsets de página están limitados
        al rango de 0 a 100000.
      operationId: get-news
      parameters:
        - description: Especificar el formato de la respuesta
          in: header
          name: accept
          required: true
          schema:
            type: string
            enum:
              - application/json
              - application/xml
            default: application/json
        - description: Desplazamiento de página. Por motivos de optimización, rendimiento
            y razones técnicas, los desplazamientos de página están limitados de
            0 a 100000. Limite los resultados de la consulta mediante otros
            parámetros, como la fecha.
          in: query
          name: page
          schema:
            type: integer
            default: 0
        - description: Cantidad de resultados devueltos. Máximo 100.
          in: query
          name: pageSize
          schema:
            type: integer
            maximum: 100
            default: 15
        - description: Especifica si deseas solo el titular (headline), el titular +
            resumen (abstract) o el titular + cuerpo completo (full) del texto
          in: query
          name: displayOutput
          schema:
            type: string
            enum:
              - full
              - abstract
              - headline
            default: headline
        - description: "La fecha para consultar noticias. Equivale a usar dateFrom y
            dateTo con el mismo valor. Formato: yyyy-mm-dd"
          in: query
          name: date
          schema:
            type: string
        - description: "Fecha a partir de la cual se realiza la consulta. Ordenado por
            fecha de publicación. Formato: yyyy-mm-dd"
          in: query
          name: dateFrom
          schema:
            type: string
        - description: "Fecha hasta la cual realizar la consulta. Ordenado por fecha de
            publicación. Formato: aaaa-mm-dd"
          in: query
          name: dateTo
          schema:
            type: string
        - description: Última marca de tiempo Unix (UTC) de actualización para extraer y
            ordenar
          in: query
          name: updatedSince
          schema:
            type: integer
        - description: Última marca de tiempo Unix (UTC) publicada para extraer y ordenar
            los datos
          in: query
          name: publishedSince
          schema:
            type: integer
        - description: "Permite controlar cómo se ordenan los resultados. El valor
            predeterminado es created, DESC. Formato: campo:sentido. Campos de
            ordenación: id, created, updated. Orden de clasificación: asc
            (ascendente), desc (descendente)"
          in: query
          name: sort
          schema:
            type: string
            enum:
              - id:asc
              - id:desc
              - created:asc
              - created:desc
              - updated:asc
              - updated:desc
        - description: "Uno o más códigos ISIN separados por comas. Máximo 50. Formato: CSV"
          in: query
          name: isin
          schema:
            type: string
        - description: "Uno o más CUSIP separados por comas. Máximo 50. Requiere acuerdo
            de licencia. Formato: CSV"
          in: query
          name: cusips
          schema:
            type: string
        - description: "Uno o más símbolos de ticker separados por comas. Máximo 50.
            Formato: csv"
          in: query
          name: tickers
          schema:
            type: string
        - description: "Uno o más símbolos de ticker primarios, separados por comas.
            Filtra únicamente por asociación de ticker primario. Formato: CSV"
          in: query
          name: primaryTickers
          schema:
            type: string
        - description: "Uno o varios nombres o ID de canal, separados por comas. Formato:
            CSV"
          in: query
          name: channels
          schema:
            type: string
        - description: "Una o más palabras o frases separadas por comas; realiza la
            búsqueda en Title, Tags y Body por orden de prioridad. Formato: CSV"
          in: query
          name: topics
          schema:
            type: string
        - description: Operador lógico para la consulta de temas. Usa 'and' para requerir
            todos los temas y 'or' para requerir cualquiera de ellos
          in: query
          name: topic_group_by
          schema:
            type: string
            enum:
              - and
              - or
            default: or
        - description: "Uno o más autores separados por una coma. Formato: CSV"
          in: query
          name: authors
          schema:
            type: string
        - description: "Uno o más tipos de contenido separados por coma. Formato: CSV"
          in: query
          name: content_types
          schema:
            type: string
        - description: Especifique el formato deseado de la respuesta de la api
          in: query
          name: format
          schema:
            type: string
            enum:
              - text
        - description: Filtrar por importancia
          in: query
          name: importance
          schema:
            type: string
        - description: Filtrar por región (p. ej., 'ca' o 'canada' para contenido
            canadiense)
          in: query
          name: region
          schema:
            type: string
      responses:
        "200":
          description: éxito
          content:
            application/json:
              schema:
                items:
                  $ref: "#/components/schemas/api.NewsItem"
                type: array
            text/xml:
              schema:
                items:
                  $ref: "#/components/schemas/api.NewsItem"
                type: array
        "400":
          description: Parámetros de consulta no válidos o faltantes
          content:
            application/json:
              schema:
                type: string
            text/xml:
              schema:
                type: string
        "499":
          description: Contexto de solicitud cancelado
          content:
            application/json:
              schema:
                type: string
            text/xml:
              schema:
                type: string
        "500":
          description: Error interno
          content:
            application/json:
              schema:
                type: string
            text/xml:
              schema:
                type: string
      security:
        - ApiKeyAuth: []
      summary: Obtener las noticias
      tags:
        - News
  /api/v2/news-removed:
    get:
      description: Devuelve los datos de noticias eliminadas. Filtra los resultados
        para incluir únicamente los elementos que se hayan actualizado desde la
        marca de tiempo indicada.
      operationId: get-removed-news
      parameters:
        - description: Especifica el formato de respuesta
          in: header
          name: accept
          required: true
          schema:
            type: string
            enum:
              - application/json
            default: application/json
        - description: Desplazamiento de página. Por motivos de optimización, rendimiento
            y razones técnicas, los desplazamientos de página están acotados al
            rango 0‑100000. Restringe los resultados de la consulta utilizando
            otros parámetros, como la fecha.
          in: query
          name: page
          schema:
            type: integer
            default: 0
        - description: Número de resultados devueltos. Máximo 100.
          in: query
          name: pageSize
          schema:
            type: integer
            maximum: 100
            default: 15
        - description: Filtra los resultados para incluir únicamente los elementos que se
            hayan actualizado desde la marca de tiempo Unix (UTC) especificada
          in: query
          name: updatedSince
          schema:
            type: integer
      responses:
        "200":
          description: éxito
          content:
            application/json:
              schema:
                additionalProperties:
                  items:
                    $ref: "#/components/schemas/api.NewsRemovedItem"
                  type: array
                type: object
        "400":
          description: Parámetros de consulta no válidos o faltantes
          content:
            application/json:
              schema:
                type: string
        "499":
          description: Contexto de la solicitud cancelado
          content:
            application/json:
              schema:
                type: string
        "500":
          description: Error interno
          content:
            application/json:
              schema:
                type: string
      security:
        - ApiKeyAuth: []
      summary: Devuelve los datos de noticias eliminadas
      tags:
        - News
servers:
  - url: //api.benzinga.com/api/v2
components:
  securitySchemes:
    ApiKeyAuth:
      description: Autenticación con clave de API. Incluya su clave de API como
        parámetro de consulta.
      in: query
      name: token
      type: apiKey
  schemas:
    api.ChannelTag:
      description: Nombre del canal o etiqueta
      properties:
        name:
          example: Technology
          type: string
      type: object
    api.Image:
      description: Imagen del artículo con tamaño y url
      properties:
        size:
          example: large
          type: string
        url:
          example: https://cdn.benzinga.com/files/images/story/2024/example.jpg
          type: string
      type: object
    api.NewsItem:
      description: Elemento de noticia con metadatos completos
      properties:
        author:
          example: Benzinga Newsdesk
          type: string
        body:
          type: string
        channels:
          items:
            $ref: "#/components/schemas/api.ChannelTag"
          type: array
        created:
          example: Wed, 17 May 2017 14:20:15 -0400
          type: string
        id:
          example: 123456
          type: integer
        image:
          items:
            $ref: "#/components/schemas/api.Image"
          type: array
        original_id:
          type: integer
        stocks:
          items:
            $ref: "#/components/schemas/api.Stock"
          type: array
        tags:
          items:
            $ref: "#/components/schemas/api.ChannelTag"
          type: array
        teaser:
          type: string
        title:
          example: Apple Announces New iPhone
          type: string
        updated:
          example: Wed, 17 May 2017 14:20:15 -0400
          type: string
        url:
          example: https://www.benzinga.com/news/123456
          type: string
      type: object
    api.NewsRemovedItem:
      description: Noticia eliminada con ID y marca de tiempo de actualización
      properties:
        id:
          example: 123456
          type: integer
        updated:
          example: Wed, 17 May 2017 14:20:15 -0400
          type: string
      type: object
    api.Stock:
      description: Información bursátil con ticker e identificadores
      properties:
        cusip:
          example: "037833100"
          type: string
        exchange:
          example: NASDAQ
          type: string
        isin:
          example: US0378331005
          type: string
        name:
          example: AAPL
          type: string
      type: object
