openapi: 3.0.0
info:
  contact: {}
  description: توفّر واجهة برمجة تطبيقات REST هذه نقاط نهاية لاسترجاع تفاصيل
    تقارير المحللين.
  termsOfService: http://swagger.io/terms/
  title: Analyst Reports Raw Text API
  version: 1.0.0
paths:
  /analyst/reports/raw-text:
    get:
      description: يسترجع نصوص خام من تقارير أبحاث المحللين المحترفين. يعيد تقارير
        المحللين بالنص الكامل، ومذكرات البحث، وتوصيات الاستثمار الصادرة عن
        المؤسسات المالية. يتضمن بيانات وصفية للتقارير، وتغييرات في التقييمات،
        والأهداف السعرية، وتحليلات مفصلة. يعد عنصرًا أساسيًا للوصول إلى الأبحاث
        المؤسسية وقياس توجهات المحللين.
      operationId: get-analyst-reports-raw-text-data
      parameters:
        - description: "رقم الصفحة للاستخدام في آلية التقسيم إلى صفحات (Pagination). يبدأ
            الترقيم من الصفر (0 = الصفحة الأولى، 1 = الصفحة الثانية، إلخ).
            القيمة الافتراضية: 0"
          in: query
          name: page
          schema:
            type: integer
        - description: "عدد النتائج في كل صفحة. القيمة الافتراضية: 100. الحد الأقصى: 100.
            يُرجِع أحدث التقارير أولًا."
          in: query
          name: pagesize
          schema:
            type: integer
      responses:
        "200":
          description: مصفوفة لتقارير المحللين تحتوي على النص الكامل والبيانات الوصفية
          content:
            application/json:
              schema:
                items:
                  $ref: "#/components/schemas/models.AnalystReportRawText"
                type: array
        "400":
          description: طلب غير صالح - معاملات غير صالحة
          content:
            application/json:
              schema:
                items:
                  type: string
                type: array
        "500":
          description: خطأ داخلي في الخادم
          content:
            application/json:
              schema:
                items:
                  type: string
                type: array
      security:
        - ApiKeyAuth: []
      summary: تقارير بحوث المحللين
      tags:
        - Analyst Reports
components:
  securitySchemes:
    ApiKeyAuth:
      in: query
      name: token
      type: apiKey
  schemas:
    models.AnalystReportRawText:
      properties:
        date:
          example: 2024-01-09
          type: string
        exchange:
          example: NASDAQ
          type: string
        extracted_paragraphs:
          items:
            type: string
          type: array
        firm_id:
          example: GS-12345
          type: string
        id:
          example: 507f1f77bcf86cd799439011
          type: string
        ticker:
          example: AAPL
          type: string
      type: object
