openapi: 3.0.0
info:
  contact: {}
  description: توفر واجهة برمجة تطبيقات REST هذه نقاط نهاية لاسترجاع مكالمات
    المؤتمرات وملخصاتها.
  termsOfService: http://swagger.io/terms/
  title: Conference call transcripts
  version: 2.1.0
paths:
  /api/v1/transcripts/calls:
    get:
      description: استرجاع قائمة بالمكالمات مع خيارات للتصفية والترقيم الصفحي. بشكل
        افتراضي، تُعاد المكالمات ذات الحالة COMPLETED فقط. استخدم status=ALL
        لإرجاع جميع الحالات.
      operationId: get-conference-calls
      parameters:
        - description: رقم الصفحة للاستخدام في ترقيم الصفحات (يبدأ من 1)
          in: query
          name: page
          schema:
            type: integer
            default: 1
        - description: عدد العناصر المطلوب إرجاعها لكل صفحة
          in: query
          name: page_size
          schema:
            type: integer
            default: 10
        - description: تصفية حسب حالة المكالمة. القيمة الافتراضية هي COMPLETED. استخدم ALL
            لإرجاع جميع الحالات.
          in: query
          name: status
          schema:
            type: string
            default: COMPLETED
      responses:
        "200":
          description: موافق
          content:
            application/json:
              schema:
                additionalProperties: true
                type: object
        "400":
          description: طلب غير صالح
          content:
            application/json:
              schema:
                additionalProperties:
                  type: string
                type: object
        "500":
          description: خطأ داخلي في الخادم
          content:
            application/json:
              schema:
                additionalProperties:
                  type: string
                type: object
      security:
        - ApiKeyAuth: []
      summary: استرجاع جميع المكالمات
      tags:
        - calls
  /api/v1/transcripts/calls/{call_id}:
    get:
      description: استرجِع معلومات تفصيلية حول استدعاء معيّن عبر معرّفه
      operationId: get-conference-call-by-id
      parameters:
        - description: المعرّف الفريد لمكالمة المؤتمر
          in: path
          name: call_id
          required: true
          schema:
            type: string
        - description: إذا كانت القيمة true، يتم تضمين عناوين url موقَّعة مسبقًا لتسجيلات
            الصوت
          in: query
          name: audio
          schema:
            type: boolean
        - description: إذا كانت القيمة true، يتضمّن عناوين URL موقَّعة مسبقًا لمحضر الجلسة
            بصيغة PDF
          in: query
          name: pdf
          schema:
            type: boolean
        - description: إذا كانت القيمة true، يُرجِع مخرجات أنظف وأكثر تبسيطًا
          in: query
          name: clean
          schema:
            type: boolean
        - description: "صيغة الاستجابة (مثال: 'json' أو 'html')"
          in: query
          name: format
          schema:
            type: string
      responses:
        "200":
          description: موافق
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/domain.Calls"
        "400":
          description: طلب غير صحيح
          content:
            application/json:
              schema:
                additionalProperties:
                  type: string
                type: object
        "404":
          description: غير موجود
          content:
            application/json:
              schema:
                additionalProperties:
                  type: string
                type: object
        "500":
          description: خطأ داخلي في الخادم
          content:
            application/json:
              schema:
                additionalProperties:
                  type: string
                type: object
      security:
        - ApiKeyAuth: []
      summary: جلب الاستدعاء بالمعرّف
      tags:
        - calls
  /api/v1/transcripts/summaries:
    get:
      description: استرجاع قائمة بالملخصات مع دعم تقسيم الصفحات
      operationId: get-summaries
      parameters:
        - description: رقم الصفحة في ترقيم الصفحات (يبدأ من 1)
          in: query
          name: page
          schema:
            type: integer
            default: 1
        - description: عدد العناصر التي تُعاد في كل صفحة
          in: query
          name: page_size
          schema:
            type: integer
            default: 10
      responses:
        "200":
          description: حسنًا
          content:
            application/json:
              schema:
                additionalProperties: true
                type: object
        "400":
          description: طلب غير صحيح
          content:
            application/json:
              schema:
                additionalProperties:
                  type: string
                type: object
        "500":
          description: خطأ داخلي في الخادم
          content:
            application/json:
              schema:
                additionalProperties:
                  type: string
                type: object
      security:
        - ApiKeyAuth: []
      summary: جلب الملخصات
      tags:
        - summaries
  /api/v1/transcripts/summaries/{call_id}:
    get:
      description: استرداد التفاصيل الموجزة لمعرّف مكالمة معيّن
      operationId: get-summary-by-call-id
      parameters:
        - description: المعرّف الفريد للمكالمة المرتبطة بهذا الملخّص
          in: path
          name: call_id
          required: true
          schema:
            type: string
      responses:
        "200":
          description: موافق
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/domain.Summaries"
        "404":
          description: غير موجود
          content:
            application/json:
              schema:
                additionalProperties:
                  type: string
                type: object
        "500":
          description: خطأ داخلي في الخادم
          content:
            application/json:
              schema:
                additionalProperties:
                  type: string
                type: object
      security:
        - ApiKeyAuth: []
      summary: استرجاع الملخص باستخدام معرّف المكالمة
      tags:
        - summaries
components:
  securitySchemes:
    ApiKeyAuth:
      in: query
      name: token
      type: apiKey
  schemas:
    domain.Calls:
      properties:
        call_id:
          example: 80753086-444f-4dcf-961d-15509ba09dc7
          type: string
        call_title:
          example: Q3 2023 Earnings Call
          type: string
        created_at:
          type: string
        deleted_at:
          type: string
        description:
          example: Quarterly earnings report
          type: string
        duration:
          example: 60
          type: integer
        end_time:
          example: 2023-10-25T15:00:00Z
          type: string
        exchange:
          example: NASDAQ
          type: string
        figis:
          example:
            - '["BBG000B9XRY4"]'
          items:
            type: string
          type: array
        headline:
          example: Company X Reports Strong Q3 Results
          type: string
        name:
          example: Apple Inc.
          type: string
        participants:
          items:
            $ref: "#/components/schemas/domain.Participants"
          type: array
        period:
          example: Q3
          type: string
        recordings:
          items:
            $ref: "#/components/schemas/domain.Recordings"
          type: array
        securities:
          $ref: "#/components/schemas/pgtype.JSONB"
        start_time:
          example: 2023-10-25T14:00:00Z
          type: string
        status:
          example: completed
          type: string
        summary:
          $ref: "#/components/schemas/domain.Summaries"
        symbol:
          example: AAPL
          type: string
        transcripts:
          items:
            $ref: "#/components/schemas/domain.Transcripts"
          type: array
        updated_at:
          type: string
        webcast_url:
          example: https://example.com/webcast
          type: string
        year:
          example: 2023
          type: integer
      type: object
    domain.Participants:
      properties:
        call_id:
          type: string
        deleted_at:
          type: string
        human_verified:
          type: boolean
        mentions:
          type: integer
        name:
          type: string
        organization:
          type: string
        participant_id:
          type: string
        role:
          type: string
      type: object
    domain.Recordings:
      properties:
        bucket:
          type: string
        created_at:
          type: string
        duration:
          type: integer
        formats:
          $ref: "#/components/schemas/pgtype.JSONB"
        language:
          type: string
        location:
          type: string
        recording_id:
          type: string
        total_files:
          type: integer
        total_size:
          type: integer
        updated_at:
          type: string
      type: object
    domain.Summaries:
      properties:
        call_id:
          example: 770e8400-e29b-41d4-a716-446655440000
          type: string
        created_at:
          type: string
        deleted_at:
          type: string
        language:
          example: en
          type: string
        sentiment:
          example: 0.85
          type: number
        summary:
          example: The company reported positive growth...
          type: string
        summary_id:
          example: 550e8400-e29b-41d4-a716-446655440000
          type: string
        symbol:
          example: MSFT
          type: string
        transcript_id:
          example: 660e8400-e29b-41d4-a716-446655440000
          type: string
        updated_at:
          type: string
      type: object
    domain.TranscriptSegments:
      properties:
        confidence:
          type: number
        end_time:
          type: string
        segment_id:
          type: integer
        sentiment:
          type: number
        speaker:
          type: string
        start_time:
          type: string
        text:
          type: string
      type: object
    domain.Transcripts:
      properties:
        confidence_score:
          type: number
        language:
          type: string
        segments:
          items:
            $ref: "#/components/schemas/domain.TranscriptSegments"
          type: array
        text:
          type: string
        transcript_id:
          type: string
        type:
          $ref: "#/components/schemas/domain.TranscriptsType"
      type: object
    domain.TranscriptsType:
      enum:
        - LIVE
        - NON_LIVE
      type: string
      x-enum-varnames:
        - LiveTranscripts
        - NonLiveTranscripts
    pgtype.JSONB:
      properties:
        bytes:
          items:
            type: integer
          type: array
        status:
          $ref: "#/components/schemas/pgtype.Status"
      type: object
    pgtype.Status:
      enum:
        - 0
        - 1
        - 2
      type: integer
      x-enum-varnames:
        - Undefined
        - "Null"
        - Present
servers:
  - url: https://api.benzinga.com/api/v1
    description: PROD
