openapi: 3.0.0
info:
  contact: {}
  description: مصادقة Bearer token
  title: Press Releases v2
  version: 2.0.0
paths:
  /api/v2/news:
    get:
      description: تعيد واجهة برمجة التطبيقات API هذه القائمة على REST بيانات منظَّمة
        للبيانات الصحفية. للحصول على أفضل أداء، قصِّر نطاق الاستعلام باستخدام
        معلمات مثل رموز الأسهم والتاريخ والقنوات، أو استخدم updatedSince للحصول
        على التغييرات فقط. إزاحات الصفحات محدودة بين 0 و100000.
      operationId: get-press-releases
      parameters:
        - description: حدِّد تنسيق الإرجاع
          in: header
          name: accept
          required: true
          schema:
            type: string
            enum:
              - application/json
              - application/xml
            default: application/json
        - description: إزاحة الصفحة. لأسباب تتعلق بالتحسين والأداء والجوانب التقنية، تقتصر
            إزاحات الصفحات على نطاق من 0 إلى 100000. قلِّص نتائج الاستعلام
            باستخدام معلمات أخرى مثل التاريخ.
          in: query
          name: page
          schema:
            type: integer
            default: 0
        - description: عدد النتائج المُعادة. الحد الأقصى 100.
          in: query
          name: pageSize
          schema:
            type: integer
            maximum: 100
            default: 15
        - description: حدِّد العنوان فقط (headline)، أو العنوان + الموجز (abstract)، أو
            العنوان + النص الكامل (full)
          in: query
          name: displayOutput
          schema:
            type: string
            enum:
              - full
              - abstract
              - headline
            default: headline
        - description: "التاريخ المطلوب الاستعلام عنه للأخبار. اختصار لـ dateFrom وdateTo
            إذا كانا متطابقين. التنسيق: yyyy-mm-dd"
          in: query
          name: date
          schema:
            type: string
        - description: "تاريخ بدء الاستعلام. يتم الترتيب حسب تاريخ النشر. التنسيق:
            yyyy-mm-dd"
          in: query
          name: dateFrom
          schema:
            type: string
        - description: "تاريخ انتهاء الاستعلام. يتم الترتيب حسب تاريخ النشر. التنسيق:
            yyyy-mm-dd"
          in: query
          name: dateTo
          schema:
            type: string
        - description: آخر طابع زمني Unix ‏(UTC) للتحديث للسحب والترتيب بناءً عليه
          in: query
          name: updatedSince
          schema:
            type: integer
        - description: آخر طابع زمني Unix ‏(UTC) للنشر للسحب والترتيب بناءً عليه
          in: query
          name: publishedSince
          schema:
            type: integer
        - description: "يتيح التحكم في فرز النتائج. القيمة الافتراضية هي created, DESC.
            التنسيق: field:direction. حقول الفرز: id, created, updated. ترتيب
            الفرز: asc (تصاعدي)، desc (تنازلي)"
          in: query
          name: sort
          schema:
            type: string
            enum:
              - id:asc
              - id:desc
              - created:asc
              - created:desc
              - updated:asc
              - updated:desc
        - description: "رقم التعريف الدولي للأوراق المالية ISIN واحد أو أكثر، مفصولة
            بفواصل. الحد الأقصى 50. التنسيق: csv"
          in: query
          name: isin
          schema:
            type: string
        - description: "قيمة CUSIP واحدة أو أكثر، مفصولة بفواصل. الحد الأقصى 50. يتطلب
            اتفاقية ترخيص. التنسيق: csv"
          in: query
          name: cusips
          schema:
            type: string
        - description: "رمز تداول واحد أو أكثر، مفصولة بفواصل. الحد الأقصى 50. التنسيق: csv"
          in: query
          name: tickers
          schema:
            type: string
        - description: "رمز تداول أساسي واحد أو أكثر، مفصولة بفواصل. تُطبَّق التصفية حسب
            الارتباط برمز التداول الأساسي فقط. التنسيق: csv"
          in: query
          name: primaryTickers
          schema:
            type: string
        - description: "اسم قناة واحد أو أكثر أو معرّفات، مفصولة بفواصل. التنسيق: csv"
          in: query
          name: channels
          schema:
            type: string
        - description: "كلمة أو عبارة واحدة أو أكثر، مفصولة بفواصل؛ يجري البحث في العنوان
            والوسوم والمتن حسب ترتيب الأولوية. التنسيق: csv"
          in: query
          name: topics
          schema:
            type: string
        - description: المعامل المنطقي لاستعلام الموضوعات. استخدم 'and' لاشتراط جميع
            الموضوعات، و'or' لاشتراط أي موضوع
          in: query
          name: topic_group_by
          schema:
            type: string
            enum:
              - and
              - or
            default: or
        - description: "مؤلف واحد أو أكثر، مفصولة بفواصل. التنسيق: csv"
          in: query
          name: authors
          schema:
            type: string
        - description: "نوع محتوى واحد أو أكثر، مفصولة بفواصل. التنسيق: csv"
          in: query
          name: content_types
          schema:
            type: string
            default: accesswire_story,accesswire_pr,businesswire_story,newswire_pressreleases,newswire_story,globenewswire_story,newsfile_story
        - description: حدِّد التنسيق المطلوب لاستجابة api
          in: query
          name: format
          schema:
            type: string
            enum:
              - text
        - description: التصفية حسب مستوى الأهمية
          in: query
          name: importance
          schema:
            type: string
            enum:
              - low
              - medium
              - high
        - description: التصفية حسب المنطقة (مثل 'ca' أو 'canada' للمحتوى الكندي)
          in: query
          name: region
          schema:
            type: string
      responses:
        "200":
          description: نجاح
          content:
            application/json:
              schema:
                items:
                  $ref: "#/components/schemas/api.NewsItem"
                type: array
            text/xml:
              schema:
                items:
                  $ref: "#/components/schemas/api.NewsItem"
                type: array
        "400":
          description: معلمات استعلام غير صالحة أو مفقودة
          content:
            application/json:
              schema:
                type: string
            text/xml:
              schema:
                type: string
        "499":
          description: تم إلغاء سياق الطلب
          content:
            application/json:
              schema:
                type: string
            text/xml:
              schema:
                type: string
        "500":
          description: خطأ داخلي
          content:
            application/json:
              schema:
                type: string
            text/xml:
              schema:
                type: string
      security:
        - ApiKeyAuth: []
      summary: البيانات الصحفية
      tags:
        - Press Releases
components:
  securitySchemes:
    ApiKeyAuth:
      description: مصادقة مفتاح واجهة برمجة التطبيقات API. قدِّم مفتاح API الخاص بك
        كمعلمة استعلام.
      in: query
      name: token
      type: apiKey
  schemas:
    api.ChannelTag:
      description: اسم القناة أو الوسم
      properties:
        name:
          example: Technology
          type: string
      type: object
    api.Image:
      description: صورة الخبر مع الحجم وURL
      properties:
        size:
          example: large
          type: string
        url:
          example: https://cdn.benzinga.com/files/images/story/2024/example.jpg
          type: string
      type: object
    api.NewsItem:
      description: عنصر خبر يتضمن بيانات وصفية كاملة
      properties:
        author:
          example: Benzinga Newsdesk
          type: string
        body:
          type: string
        channels:
          items:
            $ref: "#/components/schemas/api.ChannelTag"
          type: array
        created:
          example: Wed, 17 May 2017 14:20:15 -0400
          type: string
        id:
          example: 123456
          type: integer
        image:
          items:
            $ref: "#/components/schemas/api.Image"
          type: array
        original_id:
          type: integer
        stocks:
          items:
            $ref: "#/components/schemas/api.Stock"
          type: array
        tags:
          items:
            $ref: "#/components/schemas/api.ChannelTag"
          type: array
        teaser:
          type: string
        title:
          example: Apple Announces New iPhone
          type: string
        updated:
          example: Wed, 17 May 2017 14:20:15 -0400
          type: string
        url:
          example: https://www.benzinga.com/news/123456
          type: string
      type: object
    api.NewsRemovedItem:
      description: خبر محذوف مع المعرّف والطابع الزمني للتحديث
      properties:
        id:
          example: 123456
          type: integer
        updated:
          example: Wed, 17 May 2017 14:20:15 -0400
          type: string
      type: object
    api.Stock:
      description: معلومات السهم مع رمز التداول والمُعرّفات
      properties:
        cusip:
          example: "037833100"
          type: string
        exchange:
          example: NASDAQ
          type: string
        isin:
          example: US0378331005
          type: string
        name:
          example: AAPL
          type: string
      type: object
servers:
  - url: https://api.benzinga.com
    description: PROD
